name: Deploy GH Pages (client)
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Prepare site
        run: |
          mkdir -p site
          if [ ! -f site/index.html ]; then
            echo '<!doctype html><meta http-equiv="refresh" content="0; url=site/index.html">' > index.html
          fi
      - name: Push to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git branch gh-pages || true
          git checkout gh-pages
          git checkout main -- site
          echo '<!doctype html><meta http-equiv="refresh" content="0; url=site/index.html">' > index.html
          git add -A
          git commit -m "Update site" || true
          git push origin gh-pages
